"""Trace -> Detox test file (T6, the PROOF artifact).

RN pivot (amendment): generated tests are Detox JS (RN's de-facto E2E
framework), not XCUITest Swift. `detox test` going green once is the
third-party verification that the generated artifact is real.

Pure function: Trace in, .test.js string out. This is the demo-critical
component most prone to silent breakage, so it has a fixture-driven unit
test (T7) — no simulator needed.

Edge cases the codegen MUST handle (covered by tests/fixtures/trace_nasty.json):
  - quotes / unicode in labels  -> proper JS string escaping
  - missing a11y_id             -> fallback selector (by.text / by.label)
  - empty assertions            -> still emits a valid (navigation-only) test
  - multi-flow                  -> one describe() per flow, one it() per flow
"""

from __future__ import annotations

from trace import Action, Assertion, Flow, Target, Trace


def generate(trace: Trace) -> str:
    """Render a full Detox spec from a Trace. Each Flow -> one it(); each
    Step -> a Detox action; each Assertion -> a Detox expect(). Provenance
    comment names the flow's gbrain_symbols."""
    lines: list[str] = [
        "// Generated by ios-test from trace schema v"
        f"{trace.schema_version}. Do not edit by hand.",
        "",
        "describe('ios-test generated flows', () => {",
    ]

    for flow in trace.flows:
        lines.extend(_flow(flow))

    lines.append("});")
    lines.append("")
    return "\n".join(lines)


def _flow(flow: Flow) -> list[str]:
    title = _escape_js(flow.name)
    symbols = ", ".join(flow.gbrain_symbols) if flow.gbrain_symbols else "unknown"
    lines = [
        f"  it('{title}', async () => {{",
        f"    // Exercises: {symbols}",
    ]
    for step in flow.steps:
        if step.action == Action.LAUNCH:
            lines.append("    await device.launchApp({ newInstance: true });")
        elif step.action == Action.BACK:
            lines.append("    await device.pressBack();")
        elif step.action == Action.TAP:
            if step.target is None:
                raise ValueError(f"{flow.name}: tap step missing target")
            lines.append(f"    await element({_selector(step.target)}).tap();")
        elif step.action == Action.TYPE:
            if step.target is None:
                raise ValueError(f"{flow.name}: type step missing target")
            value = _escape_js(step.value or "")
            lines.append(f"    await element({_selector(step.target)}).typeText('{value}');")
        elif step.action == Action.SWIPE:
            if step.target is None:
                raise ValueError(f"{flow.name}: swipe step missing target")
            direction = _escape_js(step.value or "up")
            lines.append(
                f"    await element({_selector(step.target)}).swipe('{direction}');"
            )
        else:
            raise ValueError(f"{flow.name}: unsupported action {step.action}")

        for assertion in step.assertions:
            lines.extend(_assertion(assertion))

    lines.extend(["  });", ""])
    return lines


def _assertion(assertion: Assertion) -> list[str]:
    selector = f"by.id('{_escape_js(assertion.selector)}')"
    subject = f"element({selector})"
    if assertion.kind == "exists":
        return [f"    await expect({subject}).toExist();"]
    if assertion.kind == "absent":
        return [f"    await expect({subject}).not.toExist();"]
    if assertion.kind == "text_contains":
        expected = _escape_js(str(assertion.expected))
        return [f"    await expect({subject}).toHaveText(expect.stringContaining('{expected}'));"]
    if assertion.kind == "value_equals":
        expected = _escape_js(str(assertion.expected))
        return [f"    await expect({subject}).toHaveText('{expected}');"]
    raise ValueError(f"unsupported assertion kind {assertion.kind!r}")


def _selector(target: Target) -> str:
    """Detox selector from a Target, locked fallback order:
    by.id(testID) -> by.label -> by.text. Coordinate targets are flagged for
    source_patcher (brittle in a durable suite)."""
    if target.a11y_id:
        return f"by.id('{_escape_js(target.a11y_id)}')"
    if target.label:
        return f"by.label('{_escape_js(target.label)}')"
    if target.text:
        return f"by.text('{_escape_js(target.text)}')"
    if target.coord:
        x, y = target.coord
        # Coordinates are intentionally conspicuous: source_patcher should
        # turn these into stable testIDs before a durable Detox suite is kept.
        return f"by.type('RCTRootView').withAncestor(by.type('RCTRootView')) /* coord:{x},{y} */"
    raise ValueError("target has no usable selector")


def _escape_js(s: str) -> str:
    """Safe JS single-quoted string literal. The nasty-fixture test asserts
    quotes/newlines/unicode survive a `swiftc`-equivalent parse (node --check)."""
    return (
        s.replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\u2028", "\\u2028")
        .replace("\u2029", "\\u2029")
    )
